baseURL = 'https://kpu-mdsc-site.vercel.app/'
languageCode = 'ja-JP'
title = 'KPU-数理・DSセンター（非公式）'
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  disableSpecial1stPost = true
  ShowPostNavLinks = true
  ShowReadingTime = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowPostCategories = true
  ShowPostTags = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "教育プログラム"
    url = "/education/"
    weight = 10